### ISSUE TITLE
Choose a Location!!!!! 

### ISSUE THREAD

**Issue by artisanvaultcode** [GoHighLevel/oauth-demo#1]
A use case I have is a backedn service , my app is connected to this server, and the server will access gohiglevel, with this ouath and the other steps to confirm , will be kind of complex

is theres any other way to get a token an access any location whithout having to authenticate to everysingle subaccount ??

why this needs to be very odd way of ouath???

**Comment by hl-aaditya** [comment]
We have another flow for that. You'll need the agency level access token for it. 
Docs - https://highlevel.stoplight.io/docs/integrations/1a30b217da571-get-location-access-token-from-agency-token
